global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8000"]
  - job_name: "ml-service"
    static_configs:
      - targets: ["ml-service:8081"]
